### ISSUE TITLE
English translation of the CurseForge description

### ISSUE THREAD

**Issue by Jessifir** [ate47/XrayRift#6]
Since English isn't your first language, I thought I'd give you a quick tip to help your mod present itself better to English speakers.

The description would be best translated as: 

> Bored by finding your diamonds legitimately? This mod is for you!

This will be much more readable to English speakers and will help your mod stand out better in the listing.

**Comment by ate47** [comment]
Thanks, it's edited and will be changed in future mod descriptions.
